name: flutter_calendar_app
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0' 

dependencies:
  flutter:
    sdk: flutter
 
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  sqflite: ^2.3.3+1        
  path: ^1.9.0             
  intl: ^0.19.0             
  google_fonts: ^6.2.1    
  table_calendar: ^3.1.2    
  animate_do: ^3.3.4        
  flutter_quill: ^9.3.15   
  fl_chart: ^0.68.0
  shared_preferences: ^2.2.2
  flutter_heatmap_calendar: ^1.0.5
  sqflite_common_ffi: ^2.3.6 
  sqflite_common: ^2.5.6
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  cloud_firestore: ^5.0.0
  google_sign_in: ^6.2.1
  image_picker: ^1.1.0
  firebase_storage: ^12.0.0
  url_launcher: ^6.3.2
  google_generative_ai: ^0.4.7
  http: ^1.6.0
  speech_to_text: ^7.3.0
  percent_indicator: ^4.2.5
  confetti: ^0.8.0
  flutter_local_notifications: ^17.0.0 
  timezone: ^0.9.2                      
  cached_network_image: ^3.4.1
  firebase_app_check: ^0.3.2+10


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0

dependency_overrides:
  intl: 0.20.2

flutter:
  generate: true
  
  uses-material-design: true

flutter_launcher_icons:
  android: "launcher_icon" 
  ios: true                 
  image_path: "assets/icon/icon.png" 
  min_sdk_android: 21      
